config/routes.rb
Centerology::Application.routes.draw do
  devise_for :people

  root :to => 'welcome#index'

  get 'feeds/:username' => 'welcome#feed', :as => :feed

  resources :friendships

  resources :images, :only => [:show]

  resources :findings, :only => [:create, :new, :index]

  resources :tags, :only => [:index]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @recent_images = 
    
    Image
    .all
    .joins("JOIN findings ON (findings.image_id = images.id)")
    .group("findings.image_id, images.id")
    .order("MAX(findings.created_at) DESC")
    .paginate(
      :per_page => current_per_page,
      :page => current_page, 
    )
    #TODO: figure out better homepage SQL finders/scopes
    #.select("count(*) as popularity, MAX(findings.created_at) as newness")
    #.order("newness DESC, popularity DESC, newness DESC")
  end

  def feed
    @feeder = Person.find_by_username(params[:username])
    if @feeder
      @friendship = Friendship.new
      @friendship.person_id = @feeder.id
      @friendship.friend_id = current_person.to_param
      @images = @feeder.images.paginate(
        :per_page => current_per_page,
        :page => current_page, 
      )
    else
      flash[:alert] = "feed not found"
      render :action => :index, :status => :not_found
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/feed.html.erb
<% content_for :tagline do %>
  <%=link_to(@feeder.username + "'s feed", feed_url(:username => @feeder.username))%>
<% end %>

<% content_for :sidebar do %>
  <% unless @feeder == current_person %>
    <%=form_for(@friendship) do |f| %>
      <%=f.hidden_field :person_id %>
      <%=f.hidden_field :friend_id %>
      <%=f.submit%>
    <% end %>
  <% end %>
<% end %>

<%= render :partial => "shared/image", :collection => @images, :locals => { :max_similar_images => 3 } %>

<%= will_paginate(@images, {:page_links => false, :inner_window => 1, :outer_window => 1}) %>

app/views/welcome/index.html.erb
<% content_for :tagline do %>
  <%= render :partial => "shared/tagline" %>
<% end %>

<%= render :partial => "shared/image", :collection => @recent_images, :locals => { :max_similar_images => 3 } %>

<%= will_paginate(@recent_images, {:page_links => false, :inner_window => 1, :outer_window => 1}) %>